In [1]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np

X=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

l=SVC(C=1e5,kernel='linear')
l.fit(X,y)

print('W = ',l.coef_)
print('B = ',l.intercept_)
print('Indices of the support vectors= ',l.support_)
print('Support vectors are  = ')
print(l.support_vectors_)
print('No. of Support vectors for each class= ',l.n_support_)
print('Coefficient of the support vectors within the decision function= ',np.abs(l.dual_coef_))

W =  [[ 0.25 -0.25]]
B =  [-0.75]
Indices of the support vectors=  [2 3]
Support vectors are  = 
[[ 2.  3.]
 [ 6. -1.]]
No. of Support vectors for each class=  [1 1]
Coefficient of the support vectors within the decision function=  [[0.0625 0.0625]]


In [2]:
import pandas as pd
data=pd.read_csv('/Users/Kshithija/Downloads/glass.csv')
data.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [3]:
x=data.drop('Type',axis=1)
y=data.Type


In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [5]:
linear=svm.SVC(kernel='linear')
linear.fit(x_train,y_train)

SVC(kernel='linear')

In [6]:
print(linear.support_vectors_)

[[1.51926e+00 1.32000e+01 3.33000e+00 ... 9.14000e+00 0.00000e+00
  1.10000e-01]
 [1.51977e+00 1.38100e+01 3.58000e+00 ... 8.67000e+00 6.90000e-01
  0.00000e+00]
 [1.51898e+00 1.35800e+01 3.35000e+00 ... 8.91000e+00 0.00000e+00
  0.00000e+00]
 ...
 [1.52315e+00 1.34400e+01 3.34000e+00 ... 8.83000e+00 0.00000e+00
  0.00000e+00]
 [1.51556e+00 1.38700e+01 0.00000e+00 ... 9.41000e+00 8.10000e-01
  1.00000e-02]
 [1.51640e+00 1.43700e+01 0.00000e+00 ... 9.45000e+00 5.40000e-01
  0.00000e+00]]


In [7]:
print(linear.n_support_)

[42 47  9  8  4 10]


In [8]:
y_pred=linear.predict(x_test)

In [9]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.5230769230769231


In [10]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[14 11  0  0  0  0]
 [ 4 13  0  1  2  1]
 [ 5  3  0  0  0  0]
 [ 0  1  0  2  0  1]
 [ 1  1  0  0  1  0]
 [ 0  0  0  0  0  4]]


In [11]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.58      0.56      0.57        25
           2       0.45      0.62      0.52        21
           3       0.00      0.00      0.00         8
           5       0.67      0.50      0.57         4
           6       0.33      0.33      0.33         3
           7       0.67      1.00      0.80         4

    accuracy                           0.52        65
   macro avg       0.45      0.50      0.47        65
weighted avg       0.47      0.52      0.49        65



G:\Jupyter\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
G:\Jupyter\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
G:\Jupyter\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

In [13]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [14]:
y_pred1=model1.predict(x_test)

In [15]:
y_pred2=model2.predict(x_test)

In [16]:
y_pred3=model3.predict(x_test)

In [17]:
print(accuracy_score(y_test,y_pred1))

0.3230769230769231


In [18]:
print(accuracy_score(y_test,y_pred2))

0.3230769230769231


In [19]:
print(accuracy_score(y_test,y_pred3))

0.3230769230769231
